#!/bin/bash

TMP_FILE="/tmp/ipshow.tmp"

echo "IPV4" > $TMP_FILE
echo " " >> $TMP_FILE
iptables -nvL | grep -v "0 0" >> $TMP_FILE

echo " " >> $TMP_FILE
echo "IPV6" >> $TMP_FILE
echo " " >> $TMP_FILE
ip6tables -nvL | grep -v "0 0" >> $TMP_FILE
cat $TMP_FILE
rm -rf $TMP_FILE

